### ISSUE TITLE
Use dot instead of brackets & don't auto-prepend "this"

### ISSUE THREAD

**Issue by darsain** [lazd/gulp-declare#2]
... so I could do this:

``` js
.pipe(declare({
  namespace: 'this.MyApp.templates'
}))
```

to get this:

``` js
this.MyApp = this.MyApp || {};
this.MyApp.templates = this.MyApp.templates || {};
this.MyApp.templates.App = this.MyApp.templates.App || {};
this.MyApp.templates.App.Header = /* File contents from App.Header.js */;
```

Or do this:

``` js
.pipe(declare({
  namespace: 'module.exports'
}))
```

to get this:

``` js
module = module || {};
module.exports = module.exports || {};
module.exports.App = module.exports.App || {};
module.exports.App.Header = /* File contents from App.Header.js */;
```

**Comment by darsain** [comment]
Any chance this is gonna get implemented? The proposal above gives me enough control and flexibility to declare stuff however I want. For example, I'd love to concatenate all of my templates into one module (2nd example above) so I could do:

``` js
var tmp = require('./templates.js');
tmp.foo();
tmp.bar();
```

instead of:

``` js
var tmpFoo = require('./templates/foo.js');
var tmpBar = require('./templates/bar.js');
tmpFoo();
tmpBar();
```

as calling require for each template is super annoying :/

**Comment by lazd** [comment]
@darsain, bracket notation + `JSON.stringify` are used to ensure that keys with operators and special characters don't break the output. That is, `MyFile.Template-1.hbs` cannot be written in dot notation, `MyFile.Template-1 = function() {};` is not valid JavaScript due to the fact that `-` is an operator. Furthermore, dot notation is not required for `module.exports` to work.

You can achieve the desired effect by using the [`root` option](https://github.com/lazd/gulp-declare#optionsroot):

``` js
.pipe(declare({
  root: 'module.exports',
  noRedeclare: true
})
.pipe(concat('templates.js'))
```

The output looks like this:

``` js
module.exports["App"] = module.exports["App"] || {};
module.exports["App"]["Main"] = function() { return "Main"; };
module.exports["App"]["Header"] = function() { return "Header"; };
module.exports["App"]["Footer"] = function() { return "Footer"; };
```

And the resulting module looks like this:

``` js
> require('./templates.js')
{ App: 
   { Main: [Function],
     Header: [Function],
     Footer: [Function] } }
```

**Comment by darsain** [comment]
Ya, weird filenames. Brackets make sense than.

And somehow I missed the `root` option -.- damit. Any reason why `root` and `namespace` are separate? It seems they are doing the same thing.

**Comment by lazd** [comment]
- `namespace` is the thing that the `nsdeclare` module needs to actually declare
- `root` is the thing that it declares the namespace as a property of (which is assumed to already be declared)

That is, `root` is required for bracket notation -- you can't write:

``` js
["Namespace"]["Template"] = function() {};
```

In addition, `root` is assumed to already be declared and is left entirely unmolested. You could provide `root: 'getNamespace().templates'`, so additional flexibility (and potential for abuse :wink:) is available.
